version: "3"

services:
  pgdb:
    image: postgres:12.5
    environment:
      POSTGRES_PASSWORD: #senha
    ports:
      - 5432:5432 #definir porta
    volumes:
      - ./storage:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: #email
      PGADMIN_DEFAULT_PASSWORD: #senha
    ports:
      - 15432:80 #definir porta
    depends_on:
      - pgdb
